# Chapter 4

In [1]:
import numpy as np
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [4]:
X_b = np.c_[np.ones((100, 1)), X]


In [5]:
theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [6]:
theta

array([[4.06808097],
       [2.89431027]])

In [8]:
X_new = np.array([[0], [2]])

In [9]:
X_new_b = np.c_[np.ones((2, 1)), X_new]

In [10]:
y_pred = theta.T.dot(X_new_b)

In [11]:
y_pred

array([[6.96239124, 5.78862053]])

In [12]:
X_new_b.dot(theta)

array([[4.06808097],
       [9.85670151]])

<font color='red'>Scikit-Learn Linear Regression</font>

In [13]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
lin_reg.intercept_, lin_reg.coef_

(array([4.06808097]), array([[2.89431027]]))

In [15]:
lin_reg.predict(X_new)

array([[4.06808097],
       [9.85670151]])